### ISSUE TITLE
#FilesApi fails

### ISSUE THREAD

**Issue by bdares** [OfficeDev/O365-jQuery-CORS#3]
I'm getting:

`Something went wrong! Try refreshing the page.`

when I navigate to `https://localhost:44302/#FilesApi`.

Inspector says that the ajax call in filesApiCtrl.js is failing with code 500 and body:

```
{
  "error":
  {
    "code":"-1, Microsoft.SharePoint.Client.ClientServiceException",
    "message":"Exception of type 'Microsoft.SharePoint.Client.ClientServiceException' was thrown."
  }
}
```

Login works, as does displaying `#UserData`.

I've made sure that `Read and write user files`, `Read user files` permissions on `Office 365 SharePoint Online` have been granted to the app whose clientId is in `config.js`.

The endpoint URL doesn't appear to have changed (see https://msdn.microsoft.com/en-us/office/office365/api/files-rest-operations ).

**Comment by martellaj** [comment]
Hi, @bdares. Just cloned and walked through the setup myself and was unable to repro the issue you're having. Does the account you are using have OneDrive?

**Comment by bdares** [comment]
Hi @martellaj .  The account that I'm logging in with does have OneDrive.  It's got a small tree of dummy files and folders so that the app has something to show.  

I will try again with a new ActiveDirectory and app checkout.

**Comment by bdares** [comment]
Apologies.  I didn't read the setup instructions closely enough.  In my case, it was because the account I was trying to use was for Office 365 Home, not Office 365 Business.  Switching to a Business account resolved the issue.

**Comment by martellaj** [comment]
Cool, glad you got it worked out!
