### ISSUE TITLE
Is this deprecated ?

### ISSUE THREAD

**Issue by seancull** [OfficeDev/O365-jQuery-CORS#4]
Spent quite a bit of time on this and cannot get it to work.
I have now noticed that there is a [deprecated] tag at the top of the <>code page.
Is this deprecated ? If so could someone add some text explaining what the current solution is ?
Thanks, Sean

**Comment by davidchesnut** [comment]
@seancull I'm about to archive this repo and saw this quite old issue you submitted. Sorry no one responded to this sooner. There are two new auth samples we recently published at https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth and working through Microsoft Graph is the solution now. Hope this helps!
