### ISSUE TITLE
ADAL error occurred : FilesApi

### ISSUE THREAD

**Issue by MarkoSxM** [OfficeDev/O365-jQuery-CORS#5]
Hi, i've done every step of the tutorial and I still have this error when  I try to access to the FilesApi ( even when i'm connected ) :

> ADAL error occurred: AADSTS65001: The user or administrator has not consented to use the application with ID 'XXXXXXXXXXXXXXXXX' named 'XXXXXXX'. Send an interactive authorization request for this user and resource. Trace ID: e895270f-e3a3-4822-b9ec-cccc1cd34500 Correlation ID: c77f2941-d11a-42c0-8b27-0f62518d1b0f Timestamp: 2017-12-28 13:34:39Z

I've checked the Read users' files so I really don't understand why it didnt work.
If someone could help me i'll appreciate.

Thanks.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
